---
application:
  name: "algoschool-backend"
  project: "algoschool-backend"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "algoschool-backend-db"
  version: "11"
- type: "REDIS"
  name: "algoschool-backend-redis"
  version: "6"
routers:
- name: "main-algoschool-backend"
  routes:
  - application_name: "algoschool-backend"
    paths:
    - "/*"
