name: build-and-push-backend
on:
  push:
    paths:
    - 'algoschool-frontend/**'
    branches:
    - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: cr.yandex/crpv06svv8mf1emv94vs
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: cr.yandex/crpv06svv8mf1emv94vs/frontend
          tags: |
            type=raw,latest
            type=sha
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: algoschool-frontend
          file: ./algoschool-frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}