name: build-and-push-backend
on:
  push:
    paths:
    - 'algoschool-backend/**'
    branches:
    - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: cr.yandex
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: algoschool-backend
          file: ./algoschool-backend/Dockerfile
          push: true
          tags: crpv06svv8mf1emv94vs/backend:latest