name: 'Deploy latest containers on a server'
on:
  workflow_dispatch:
jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
      - name: "Run deploy on a server"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
          script: |
            sudo docker-compose -f docker-compose.yaml pull
            sudo docker-compose -f docker-compose.yaml up -d
